In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
# Dense: to add layers (hidden,output)
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
# sequential: to add layers in sequence, to initialize ann model i.e, initially random weight will be assigned
from sklearn.metrics import classification_report
import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv("/content/Churn_Modelling.csv")
df
# exited is a target column. binary classification problem


RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [3]:
df.drop(columns=['RowNumber','CustomerId','Surname'],inplace=True)

## **Data Transformation**

In [4]:
df.isna().sum( )

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [5]:
df

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [6]:
df=pd.get_dummies(data=df,columns=['Geography','Gender'])
df

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0                  1        101348.88       1              True   
1                  1        112542.58       0             False   
2                  0        113931.57       1              True   
3                  0         93826.63       0              True   
4                  1         79084.10       0             False   
...              ...              ...     ...               ...   
9995               0         96270.64       0              True   
9996               1        101699.77       0              True   
9997               1         42085.58       1              True   
9998               0         92888.52       1             False   
9999               0         38190.78       0              True   

      Geography_Germany  Geography_Spain  Gender_Female  Gender_Male  
0                 False            False           True        False  
1                 False             True           True        False  
2                 False            False           True        False  
3                 False            False           True        False  
4                 False             True           True        False  
...                 ...              ...            ...          ...  
9995              False            False          False         True  
9996              False            False          False         True  
9997              False            False           True        False  
9998               True            False          False         True  
9999              False            False           True        False  

[10000 rows x 14 columns]

In [7]:
sc=StandardScaler()
x=df.drop(columns=['Exited'])
y=df['Exited']

In [8]:
x=sc.fit_transform(x)
x

array([[-0.32622142,  0.29351742, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       [-0.44003595,  0.19816383, -1.38753759, ...,  1.74273971,
         1.09598752, -1.09598752],
       [-1.53679418,  0.29351742,  1.03290776, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [ 0.60498839, -0.27860412,  0.68712986, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 1.25683526,  0.29351742, -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [ 1.46377078, -1.04143285, -0.35020386, ..., -0.57380915,
         1.09598752, -1.09598752]])

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=1)

In [10]:
x_train

array([[-0.23310044, -0.94607926, -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [-0.25379399, -0.94607926, -0.35020386, ..., -0.57380915,
         1.09598752, -1.09598752],
       [-0.39864885,  0.77028538,  0.34135195, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [ 0.22215769,  0.5795782 ,  1.37868567, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 0.12903671,  0.00745665,  1.03290776, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 1.16371428,  0.29351742,  0.34135195, ..., -0.57380915,
        -0.91241915,  0.91241915]])

In [11]:
# create instance of sequential class
model=Sequential()

# Sequential is a class in kearas that allows you to build a model layer-by-layer
# create neurons in input, hidden and output layers and assign random weights to input
# in i/p layer 13 neurons will be there as there are 13 independent features

# Add hidden layer, randomly 10 neurons are added
model.add(Dense(units=10,activation='relu'))# as target is binary use relu activation
#Layers are added sequentially using the .add() method
# Each layer recieves input from the previous layer and passes output to the next one.

# add output layer
model.add(Dense(units=1,activation='sigmoid'))# for binary classification use sigmoid activation in output

# establish the connection b/w the layers
model.compile(optimizer='adadelta',loss='binary_crossentropy',metrics=['accuracy'])
# adadelta is gradient descent algorithm for weight updation which we have selected randomly.we will hypertune it afterly
# binary_crossentropy: also called log_loss, finds errors,range is 0 to 1

#fit the data, perform forward and back propagation
model.fit(x_train,y_train,epochs=100)
#epocs: 100 means that the model will go through the entire x_train and y_train dataset 100 times during training.
#epoch: backward and forward propagation will done for 100 times
# the no of batches per epoch=Total no of samples/Batch size(default is 32)
# 80% of training data=8000 samples.so batches=8000/32=250
# each batch is proceeded in sequence during each epoch
# and after all 250 batches are proceded,one epoch is complete

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7297 - loss: 0.5893
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7390 - loss: 0.5859
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7309 - loss: 0.5885
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7301 - loss: 0.5843
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7322 - loss: 0.5946
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7348 - loss: 0.5947
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7358 - loss: 0.5855
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7393 - loss: 0.5899
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7243 - loss: 0.5985
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7336 - loss: 0.5893
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7279 - loss: 0.5910
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━

In [12]:
x_test


array([[-1.04014895,  0.77028538, -1.04175968, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [ 0.3049319 , -0.4693113 , -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [-1.23673768,  0.29351742, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [-0.86425376, -0.4693113 ,  1.72446358, ...,  1.74273971,
        -0.91241915,  0.91241915],
       [-0.30552787, -0.85072567, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 0.0462625 ,  1.24705333,  1.37868567, ..., -0.57380915,
        -0.91241915,  0.91241915]])

In [13]:
ypred=model.predict(x_test)
ypred # in dataset target column is vlues are 0 and 1, but here output is a continuous number
# because in output layer activation function is sigmoid. it gives u o/p in tems of probability
# in sigmoid if probability is >0.5 it gives u 1 and if probability <0 it should give 0


63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


array([[0.21516867],
       [0.25203568],
       [0.22579814],
       ...,
       [0.18035623],
       [0.3078434 ],
       [0.36494917]], dtype=float32)

In [14]:
y_test

9953    0
3850    0
4962    0
3886    0
5437    0
       ..
3919    0
162     0
7903    0
2242    0
2745    0
Name: Exited, Length: 2000, dtype: int64

In [15]:
ypred>0.5

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [16]:
ypred=ypred>0.5
ypred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [17]:
print(classification_report(y_test,ypred))

              precision    recall  f1-score   support

           0       0.81      0.93      0.86      1585
           1       0.35      0.14      0.20       415

    accuracy                           0.77      2000
   macro avg       0.58      0.54      0.53      2000
weighted avg       0.71      0.77      0.73      2000



## **Hyper parameter Tuning**

In [18]:
!pip install -U keras-tuner

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.1/129.1 kB 2.3 MB/s eta 0:00:00


### **Tuning the ANN model**

In [20]:
import keras_tuner as kt


In [29]:
# tuning for best optimizer(adam,rmsprop or sgd:stochastic gradient descent)only
def optimizer_selection(hp):
  # create instence of a sequential class
  model=Sequential()
  #add hidden layer
  model.add(Dense(units=10,activation='relu'))
  # add output layer
  model.add(Dense(units=1,activation='sigmoid'))
  # optimizer selection
  optim=hp.Choice('optimizer',values=['sgd','adam','rmsprop'])# value of optimizer is categorical so use choice() function
  model.compile(optimizer=optim,loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [30]:
# similar to GridSearchCV() we will use RandomSearch()
tuner=kt.RandomSearch(
    optimizer_selection,# model name-here sequential() class is our model
    objective='val_accuracy',# increase accuracy of test data i.e, validation testv accuracy or minimize 'val_loss'
    max_trials=3 # for each optimizer take 3 trails, can select 3 to 10 or 20 for larger problems
)

In [31]:
tuner.search(x_train,y_train,epochs=3,validation_data=(x_test,y_test))
# tuner.search()is equivalent to grid.fit()
# epochs should be same as max_trails so 3 is selected
#validation_data: pass test data

Trial 3 Complete [00h 00m 03s]
val_accuracy: 0.8084999918937683

Best val_accuracy So Far: 0.8190000057220459
Total elapsed time: 00h 00m 13s


In [32]:
tuner.get_best_hyperparameters()[0].values # asper performence all optimizers are stored in an array
# we want high accuracy optimizer present at index 0 location

{'optimizer': 'adam'}

In [33]:
model=tuner.get_best_models(num_models=1)[0]# get best model: adam
model.fit(x_train,y_train,epochs=100,validation_data=(x_test,y_test))

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8194 - loss: 0.4158 - val_accuracy: 0.8265 - val_loss: 0.3965
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8274 - loss: 0.3987 - val_accuracy: 0.8360 - val_loss: 0.3859
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8377 - loss: 0.3883 - val_accuracy: 0.8405 - val_loss: 0.3766
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8377 - loss: 0.3859 - val_accuracy: 0.8435 - val_loss: 0.3712
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8372 - loss: 0.3913 - val_accuracy: 0.8455 - val_loss: 0.3673
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8490 - loss: 0.3709 - val_accuracy: 0.8465 - val_loss: 0.3630
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8495 - loss: 0.3674 - val_accuracy: 0.8485 - val_loss: 0.3603
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8483 - loss: 0.3701 - val_accu

In [34]:
model.evaluate(x_test,y_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8596 - loss: 0.3417


[0.3354091942310333, 0.8619999885559082]

# **Regression**

In [35]:
df=pd.read_csv("/content/Price.csv")
df

price     feature1     feature2
0    461.527929   999.787558   999.766096
1    548.130012   998.861615  1001.042403
2    410.297162  1000.070267   998.844015
3    540.382220   999.952251  1000.440940
4    546.024553  1000.446011  1000.338531
..          ...          ...          ...
995  476.526078  1000.018988   999.672732
996  457.313186   998.855379  1000.020026
997  456.720993  1001.451646   998.847605
998  403.315576  1000.771023   998.562851
999  599.367094   999.232244  1001.451407

[1000 rows x 3 columns]

In [36]:
x=df.iloc[:,1:]
y=df['price']

In [37]:
x=sc.fit_transform(x)
x

array([[-0.23277509, -0.22551031],
       [-1.18389307,  1.12100979],
       [ 0.05762098, -1.19831827],
       ...,
       [ 1.47655818, -1.19452982],
       [ 0.77742978, -1.49494959],
       [-0.80318737,  1.55251428]])

In [38]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=1)

In [40]:
ann=Sequential()

ann.add(Dense(units=30,activation='relu'))# hidden layer1
ann.add(Dense(units=20,activation='relu'))# hidden layer2

ann.add(Dense(units=1))# output layer
# in regression task no activation function is required in o/p layer as we don't have to convert price to 0 or 1

ann.compile(optimizer='adam',loss='mse')

ann.fit(x_train,y_train,epochs=100,validation_data=(x_test,y_test))

Epoch 1/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 255455.0781 - val_loss: 262454.1562
Epoch 2/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 256361.5938 - val_loss: 261557.6875
Epoch 3/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 256662.3906 - val_loss: 260194.5469
Epoch 4/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 253749.9531 - val_loss: 258163.2031
Epoch 5/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 248079.0312 - val_loss: 255123.0781
Epoch 6/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 248977.1094 - val_loss: 250742.2656
Epoch 7/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 245589.5938 - val_loss: 244725.2969
Epoch 8/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 236938.0781 - val_loss: 236763.5781
Epoch 9/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 226094.5781 - val_loss: 226687.2969
Epoch 10/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 217718.9688 - val_loss: 214370.0625
Epoch 11/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/s

In [41]:
yp=ann.predict(x_test)
yp

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step


array([[474.99747],
       [523.29694],
       [499.89072],
       [541.4843 ],
       [652.6239 ],
       [348.04218],
       [344.9067 ],
       [375.7851 ],
       [719.16235],
       [510.99463],
       [484.35684],
       [506.43704],
       [499.41147],
       [377.22943],
       [545.8031 ],
       [489.81592],
       [576.54895],
       [547.7734 ],
       [486.01474],
       [496.69028],
       [469.80673],
       [609.884  ],
       [440.03802],
       [575.51276],
       [421.2745 ],
       [521.2785 ],
       [388.49078],
       [497.88135],
       [539.726  ],
       [342.6387 ],
       [444.93674],
       [646.5032 ],
       [561.5334 ],
       [540.81604],
       [604.9854 ],
       [558.0125 ],
       [401.96732],
       [570.68   ],
       [565.8579 ],
       [528.5303 ],
       [419.02563],
       [729.0997 ],
       [523.5839 ],
       [528.5096 ],
       [524.41113],
       [461.2722 ],
       [533.98083],
       [523.5196 ],
       [583.9689 ],
       [466.37485],


In [42]:
from sklearn.metrics import r2_score

In [43]:
r2_score(y_test,yp)

0.9722832539306832